services:
  - type: web
    name: legacy-wallet-frontend
    env: static
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
